'use strict';
// Build the browser bundle: indicators.js + agents.js + aggregator.js -> site/engine.js
const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const OUT = path.join(ROOT, 'site', 'engine.js');

const MODS = ['indicators', 'agents', 'aggregator'];

function wrap(name) {
  const body = fs.readFileSync(path.join(ROOT, name + '.js'), 'utf8');
  return [
    `  __define('${name}', function () {`,
    `    var module = { exports: {} };`,
    `    var exports = module.exports;`,
    `    var require = __req;`,
    body,
    `    return module.exports;`,
    `  });`
  ].join('\n');
}

const banner = [
  '/* XAU/USDT OMNISCIENT SCALPER — browser engine bundle (generated by build-static.js) */',
  '(function (root) {',
  `  'use strict';`,
  `  var __m = {};`,
  `  function __define(id, factory) { __m[id] = factory(); }`,
  `  function __req(id) { id = String(id).replace(/^\\.\\//, '').replace(/\\.js$/, ''); return __m[id]; }`
].join('\n');

const tail = [
  `  root.TerminalIndicators = __req('indicators');`,
  `  root.TerminalEngine = __req('aggregator');`,
  `})(typeof window !== 'undefined' ? window : globalThis);`,
  ''
].join('\n');

fs.mkdirSync(path.join(ROOT, 'site'), { recursive: true });
fs.writeFileSync(OUT, banner + '\n' + MODS.map(wrap).join('\n') + '\n' + tail);
console.log('built', OUT, fs.statSync(OUT).size, 'bytes');
